terraform-validate:
    runs-on: ubuntu-latest
    name: Terraform Validation
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
      - name: Terraform Init
        run: |
          cd infrastructure
          terraform init -backend=false
      - name: Terraform Validate
        run: |
          cd infrastructure
          terraform validate
      - name: Run tflint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1
      - name: Show version
        run: tflint --version
      - name: Init tflint
        run: |
          cd infrastructure
          tflint --init
      - name: Run tflint
        run: |
          cd infrastructure
          tflint -f compact